In [1]:
#import module
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
#read CSV file
soya = pd.read_csv("soyabeanfinaldata.csv")

In [3]:
soya.head()

State     District Arrival_date Variety  Amount Sold  Modal_price
0  Chattisgarh  Balodabazar          Apr   Other          3.1  2933.333333
1  Chattisgarh  Balodabazar          Feb   Other         15.5  3182.928571
2  Chattisgarh  Balodabazar          Jan   Other          6.9  3144.666667
3  Chattisgarh  Balodabazar          Jul   Other          1.5  3139.750000
4  Chattisgarh  Balodabazar          Jun   Other          1.3  3160.666667

In [4]:
# create dependent and independent variable
X = soya.iloc[: , :-1].values
y = soya.iloc[:,5].values

In [5]:
#Lable Encode first column
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])

In [6]:
X

array([[0, 'Balodabazar', 'Apr', 'Other', 3.1],
       [0, 'Balodabazar', 'Feb', 'Other', 15.5],
       [0, 'Balodabazar', 'Jan', 'Other', 6.9],
       ...,
       [7, 'Lalitpur', 'Nov', 'Yellow', 8191.0],
       [7, 'Lalitpur', 'Oct', 'Yellow', 329.5],
       [7, 'Lalitpur', 'Sep', 'Yellow', 80.4]], dtype=object)

In [7]:
#Lable Encode second column
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,1] = labelencoder_X.fit_transform(X[:,1])

In [8]:
X

array([[0, 9, 'Apr', 'Other', 3.1],
       [0, 9, 'Feb', 'Other', 15.5],
       [0, 9, 'Jan', 'Other', 6.9],
       ...,
       [7, 59, 'Nov', 'Yellow', 8191.0],
       [7, 59, 'Oct', 'Yellow', 329.5],
       [7, 59, 'Sep', 'Yellow', 80.4]], dtype=object)

In [9]:
#Lable Encode Third column
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,2] = labelencoder_X.fit_transform(X[:,2])

In [10]:
X

array([[0, 9, 0, 'Other', 3.1],
       [0, 9, 2, 'Other', 15.5],
       [0, 9, 3, 'Other', 6.9],
       ...,
       [7, 59, 8, 'Yellow', 8191.0],
       [7, 59, 9, 'Yellow', 329.5],
       [7, 59, 10, 'Yellow', 80.4]], dtype=object)

In [11]:
#Lable Encode fourth column
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,3] = labelencoder_X.fit_transform(X[:,3])

In [12]:
X

array([[0, 9, 0, 2, 3.1],
       [0, 9, 2, 2, 15.5],
       [0, 9, 3, 2, 6.9],
       ...,
       [7, 59, 8, 5, 8191.0],
       [7, 59, 9, 5, 329.5],
       [7, 59, 10, 5, 80.4]], dtype=object)

In [14]:
#take onehotencoder
onehotencoder = OneHotEncoder(categorical_features = [0])
X =  onehotencoder.fit_transform(X).toarray()

In [ ]:
X

In [ ]:
pd.DataFrame(X)

In [ ]:
#take onehotencoder
onehotencoder = OneHotEncoder(categorical_features = [8])
X =  onehotencoder.fit_transform(X).toarray()

In [ ]:
pd.DataFrame(X)

In [ ]:
#take onehotencoder
onehotencoder = OneHotEncoder(categorical_features = [114])
X =  onehotencoder.fit_transform(X).toarray()

In [ ]:
#take onehotencoder
onehotencoder = OneHotEncoder(categorical_features = [125])
X =  onehotencoder.fit_transform(X).toarray()

In [ ]:
pd.DataFrame(X)

In [ ]:
# then give data to machine for training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 5)


In [ ]:
X=pd.DataFrame(X)
X

In [ ]:
y=pd.DataFrame(y)
y

In [ ]:
y  =  np.reshape(y, (-1,1))

In [ ]:
# create feature scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y =  StandardScaler()
X = sc_x.fit_transform(X)
y = sc_y.fit_transform(y)

In [ ]:
# By using SVR
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(X,y)

In [ ]:
#predict data
y_predict = regressor.predict(sc_x.fit_transform(X_test))
y_predict = sc_y.inverse_transform(y_predict)

In [ ]:
y_predict

In [ ]:
y_test

In [ ]:
# polt data between actual price and predict price
import matplotlib.pyplot as plt
plt.figure(figsize=(16,12))
plt.plot(y_test,label='actual_data',color='blue')
plt.plot(y_predict,label='yPredict_data',color='red')
plt.title(" polt data between actual price and predict price by SVR")
plt.legend()
plt.show()

In [ ]:
# polt data between actual price and predict price
import matplotlib.pyplot as plt
plt.figure(figsize=(16,12))
plt.scatter(y_test,y_predict,label='actual_data',color='blue')
plt.plot(y_predict,label='yPredict_data',color='red')
plt.title(" polt data between actual price and predict price by SVR")
plt.legend()
plt.show()